# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-09-15 00:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from campaigns.models import Campaign
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('campaigns', '0001_initial'), ('campaigns', '0002_degreeregistration'), ('campaigns', '0003_auto_20161006_0218'), ('campaigns', '0004_campaign_product'), ('campaigns', '0005_create_degree_products'), ('campaigns', '0006_auto_20161008_1538'), ('campaigns', '0007_create_attendee_types'), ('campaigns', '0008_auto_20161008_2013'), ('campaigns', '0009_degreeregistration_cost'), ('campaigns', '0010_attendeetype_product'), ('campaigns', '0011_auto_20161009_1933'), ('campaigns', '0012_auto_20161009_1953'), ('campaigns', '0013_product_meta_fields'), ('campaigns', '0014_initial_nut_prices'), ('campaigns', '0015_auto_20161106_1522'), ('campaigns', '0016_auto_20161106_1940'), ('campaigns', '0017_order_braintree_id'), ('campaigns', '0018_auto_20161106_2103'), ('campaigns', '0019_auto_20170107_2031'), ('campaigns', '0020_customer'), ('campaigns', '0021_auto_20170129_2010'), ('campaigns', '0022_auto_20170212_1425'), ('campaigns', '0023_order_claimed'), ('campaigns', '0024_campaign_lookup_name'), ('campaigns', '0025_auto_20170430_1520'), ('campaigns', '0026_campaign_header'), ('campaigns', '0027_campaign_closed'), ('campaigns', '0028_campaign_closed_message'), ('campaigns', '0029_campaign_template_name'), ('campaigns', '0030_order_extra'), ('campaigns', '0031_populate_2017golf'), ('campaigns', '0032_auto_20170707_1944'), ('campaigns', '0033_campaigntag'), ('campaigns', '0034_auto_20170724_1617'), ('campaigns', '0035_add_donation_to_2017golf'), ('campaigns', '0036_update_sponsorships'), ('campaigns', '0037_campaign_reporting_start')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_council', models.CharField(max_length=100)),
                ('attending_council_num', models.PositiveIntegerField()),
                ('candidates', models.PositiveIntegerField()),
                ('guests', models.PositiveIntegerField()),
                ('medallions', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('meta_field_one', models.CharField(max_length=100, null=True)),
                ('meta_field_two', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='degreeregistration',
            name='candidates',
        ),
        migrations.RemoveField(
            model_name='degreeregistration',
            name='guests',
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.AttendeeType'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='degree_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.DegreeRegistration'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='degree_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='campaigns.DegreeRegistration'),
        ),
        migrations.AddField(
            model_name='degreeregistration',
            name='cost',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Product'),
        ),
        migrations.DeleteModel(
            name='AttendeeType',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact',
            field=models.ManyToManyField(to='campaigns.Contact'),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('braintree_id', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.Order'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.Product'),
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-modified_time']},
        ),
        migrations.AddField(
            model_name='order',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_field_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_field_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='campaigns.Order')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='lookup_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='when',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='where',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='closed_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template_name',
            field=models.CharField(default='generic_sales', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MerchantAccountId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='merchant_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.MerchantAccountId'),
        ),
        migrations.CreateModel(
            name='CampaignTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='reporting_start',
            field=models.DateField(default=datetime.date(2016, 1, 1)),
            preserve_default=False,
        ),
    ]

