# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_council', models.CharField(max_length=100)),
                ('attending_council_num', models.PositiveIntegerField()),
                ('candidates', models.PositiveIntegerField()),
                ('guests', models.PositiveIntegerField()),
                ('medallions', models.PositiveIntegerField()),
            ],
        ),
    ]
