# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-09-15 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_squashed_0037_campaign_reporting_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
