# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-03 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20180914_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
