# Generated by Django 2.1.15 on 2020-10-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_product_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
    ]
