# Generated by Django 2.1.15 on 2020-12-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_test_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='columns',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
