# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_create_degree_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='degreeregistration',
            name='candidates',
        ),
        migrations.RemoveField(
            model_name='degreeregistration',
            name='guests',
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.AttendeeType'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='degree_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.DegreeRegistration'),
        ),
    ]
