# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_create_attendee_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='degree_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='campaigns.DegreeRegistration'),
        ),
    ]
