# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20161008_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeregistration',
            name='cost',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
