# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_auto_20161009_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact',
            field=models.ManyToManyField(to='campaigns.Contact'),
        ),
    ]
