# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_auto_20161009_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_field_one',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_field_two',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
