# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 01:43
from __future__ import unicode_literals

from django.db import migrations
from .. import models


def forwards(apps, schema_editor):
    campaign = models.Campaign.objects.create(name='Nut Sales')
    models.Product.objects.create(
        name='Pecan Halves',
        cost=12,
        campaign=campaign,
        meta_field_one='1 lb',
        meta_field_two='pecan_halves.png',
    )
    models.Product.objects.create(
        name='Praline Pecans',
        cost=10,
        campaign=campaign,
        meta_field_one='1 lb',
        meta_field_two='praline_pecans.png',
    )
    models.Product.objects.create(
        name='Cinnamon Pecans',
        cost=10,
        campaign=campaign,
        meta_field_one='1 lb',
        meta_field_two='cinnamon_pecans.png',
    )
    models.Product.objects.create(
        name='Cashews',
        cost=10,
        campaign=campaign,
        meta_field_one='14 oz',
        meta_field_two='roasted_cashews.png',
    )
    models.Product.objects.create(
        name='Walnuts',
        cost=10,
        campaign=campaign,
        meta_field_one='12 oz',
        meta_field_two='english_walnuts.png',
    )
    models.Product.objects.create(
        name='Whole Almonds',
        cost=10,
        campaign=campaign,
        meta_field_one='1 lb',
        meta_field_two='whole_almonds.png',
    )
    models.Product.objects.create(
        name='Sliced Almonds',
        cost=10,
        campaign=campaign,
        meta_field_one='12 oz',
        meta_field_two='almond_slices.png',
    )
    models.Product.objects.create(
        name='Chocolate Covered Pecans',
        cost=10,
        campaign=campaign,
        meta_field_one='1 lb',
        meta_field_two='milk_chocolate_pecans.png',
    )
    models.Product.objects.create(
        name='Chocolate Covered Almonds',
        cost=10,
        campaign=campaign,
        meta_field_one='1 lb',
        meta_field_two='milk_chocolate_almonds.png',
    )
    models.Product.objects.create(
        name='Chocolate Covered Cherries',
        cost=10,
        campaign=campaign,
        meta_field_one='14 oz',
        meta_field_two='milk_chocolate_cherries.png',
    )
    models.Product.objects.create(
        name='Pretzels (Christmas, covered)',
        cost=5,
        campaign=campaign,
        meta_field_one='14 oz',
        meta_field_two='yogurt_pretzels.png',
    )


def backwards(apps, schema_editor):
    models.Campaign.objects.get(name='Nut Sales').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_product_meta_fields'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
