# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_auto_20161106_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
