# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_auto_20161106_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
