# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_order_braintree_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-modified_time']},
        ),
        migrations.AddField(
            model_name='order',
            name='voided',
            field=models.BooleanField(default=False),
        ),
    ]
