# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_auto_20161106_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_field_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_field_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
