# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
