# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_auto_20170129_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='campaigns.Order'),
        ),
    ]
