# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_auto_20170212_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
