# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_order_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lookup_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
