# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-30 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_auto_20170430_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
