# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-30 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_campaign_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='closed_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
