# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-07 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0028_campaign_closed_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template_name',
            field=models.CharField(default='generic_sales', max_length=100),
        ),
    ]
