# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-25 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0029_campaign_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
