# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-25 19:18
from __future__ import unicode_literals

from django.db import migrations
from .. import models


def forwards(apps, schema_editor):
    campaign = models.Campaign.objects.get_or_create(
        name='2017 Golf Classic',
        lookup_name='golf2017',
        template_name='golf_registration'
    )[0]
    models.Product.objects.get_or_create(
        name='Complementary Player',
        campaign=campaign,
        cost=-125
    )
    models.Product.objects.get_or_create(
        name='Player',
        campaign=campaign,
        cost=125,
        meta_field_one='player'
    )
    models.Product.objects.get_or_create(
        name='Par Sponsor',
        campaign=campaign,
        cost=200,
        meta_field_one='sponsor-level',
        meta_field_two='Includes hole signage and 1 complimentary player entry',
        sort_order=1
    )
    models.Product.objects.get_or_create(
        name='Birdie Sponsor',
        campaign=campaign,
        cost=325,
        meta_field_one='sponsor-level',
        meta_field_two='Includes hole signage and 2 complimentary player entries',
        sort_order=2
    )
    models.Product.objects.get_or_create(
        name='Eagle Sponsor',
        campaign=campaign,
        cost=575,
        meta_field_one='sponsor-level',
        meta_field_two='Includes hole signage and 4 complimentary player entries',
        sort_order=3
    )
    models.Product.objects.get_or_create(
        name='Tournament Sponsor',
        campaign=campaign,
        cost=1500,
        meta_field_one='sponsor-level',
        meta_field_two='Includes 2 complimentary foursomes, clubhouse banner, and dinner recognition',
        sort_order=4
    )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0030_order_extra'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
