# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0031_populate_2017golf'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAccountId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='merchant_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.MerchantAccountId'),
        ),
    ]
