# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-24 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0033_campaigntag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntag',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
