# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-29 02:50
from __future__ import unicode_literals

from django.db import migrations
from .. import models


def forwards(apps, schema_editor):
    campaign = models.Campaign.objects.get_or_create(
        name='2017 Golf Classic',
        lookup_name='golf2017',
        template_name='golf_registration'
    )[0]
    models.Product.objects.get_or_create(
        name='Donation',
        campaign=campaign,
        cost=1
    )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0034_auto_20170724_1617'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
