# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-13 20:26
from __future__ import unicode_literals

from django.db import migrations
from .. import models


def forwards(apps, schema_editor):
    campaign = models.Campaign.objects.get(
        lookup_name='golf2017',
    )
    models.Product.objects.get_or_create(
        name='Platinum Sponsor',
        campaign=campaign,
        cost=5000,
        meta_field_one='sponsor-level',
        meta_field_two='Includes enhanced tournament marketing opportunities, two teams, banner at the clubhouse, special recognition at shotgun start and dinner',
        sort_order=4
    )
    models.Product.objects.get_or_create(
        name='Gold Sponsor',
        campaign=campaign,
        cost=2500,
        meta_field_one='sponsor-level',
        meta_field_two='Includes two teams, banner at the clubhouse, special recognition at shotgun start and dinner.',
        sort_order=3
    )
    models.Product.objects.get_or_create(
        name='Silver Sponsor',
        campaign=campaign,
        cost=1500,
        meta_field_one='sponsor-level',
        meta_field_two='Includes one team, banner at the clubhouse',
        sort_order=2
    )
    models.Product.objects.get_or_create(
        name='Cart Sponsor',
        campaign=campaign,
        cost=500,
        meta_field_one='sponsor-level',
        meta_field_two='Includes signage on golf course bevarage cart',
        sort_order=1
    )
    models.Product.objects.get_or_create(
        name='Hole Sponsor',
        campaign=campaign,
        cost=250,
        meta_field_one='sponsor-level',
        meta_field_two='Includes signage at the golf hole tee box',
        sort_order=0
    )


def backwards(apps, schema_editor):
    campaign = models.Campaign.objects.get(
        lookup_name='golf2017',
    )
    models.Product.objects.filter(
        name='Platinum Sponsor',
        campaign=campaign,
    ).delete()
    models.Product.objects.filter(
        name='Gold Sponsor',
        campaign=campaign,
    ).delete()
    models.Product.objects.filter(
        name='Silver Sponsor',
        campaign=campaign,
    ).delete()
    models.Product.objects.filter(
        name='Cart Sponsor',
        campaign=campaign,
    ).delete()
    models.Product.objects.filter(
        name='Hole Sponsor',
        campaign=campaign,
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0035_add_donation_to_2017golf'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
