# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-12 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0036_update_sponsorships'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='reporting_start',
            field=models.DateField(default=datetime.date(2016, 1, 1)),
            preserve_default=False,
        ),
    ]
